version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: eqsx0/kittygram_backend
    env_file: .env
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - db
    expose:
      - "8000"
  frontend:
    env_file: .env
    image: eqsx0/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: eqsx0/kittygram_gateway
    env_file: .env
    ports:
      - "8000:80"
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend
